config_file: /etc/redpanda/redpanda.yaml
node_uuid: maX5g9gESrwgmoGfKCyKJqGTxdDX7jvscFykcRFYcqp6iWrFj
pandaproxy: {}
redpanda:
  admin:
  - address: 0.0.0.0
    port: 9644
  advertised_kafka_api:
  - address: redpanda
    name: plaintext
    port: 29092
  - address: localhost
    name: outside
    port: 9092
  auto_create_topics_enabled: true
  data_directory: /var/lib/redpanda/data
  developer_mode: true
  enable_idempotence: true
  enable_transactions: true
  group_min_session_timeout_ms: 500
  kafka_api:
  - address: 0.0.0.0
    name: plaintext
    port: 29092
  - address: 0.0.0.0
    name: outside
    port: 9092
  node_id: 0
  rpc_server:
    address: 0.0.0.0
    port: 33145
  seed_servers: []
rpk:
  coredump_dir: /var/lib/redpanda/coredump
  enable_memory_locking: false
  enable_usage_stats: true
  overprovisioned: true
  tune_aio_events: false
  tune_ballast_file: false
  tune_clocksource: false
  tune_coredump: false
  tune_cpu: false
  tune_disk_irq: false
  tune_disk_nomerges: false
  tune_disk_scheduler: false
  tune_disk_write_cache: false
  tune_fstrim: false
  tune_network: false
  tune_swappiness: false
  tune_transparent_hugepages: false
schema_registry: {}
